a = "hello World2"
print(a.capitalize())
print(a.casefold())
print(a.center(20, "O"))
print(a.count("l"))
print(a.endswith("d"))
print(a.find("ll"))
txt = "For only {price:.3f} dollars!"
print(txt.format(price = 49))
print(a.index("ll"))
print(a.isalnum())
print(a.isalpha())
print(a.isdecimal()) #unicode
print(a.isdigit())
print(a.isidentifier()) #A valid identifier cannot start with a number, or contain any spaces.
print(a.islower())
print(a.isnumeric())
print(a.isprintable())
print(a.isspace())
print(a.istitle())
print(a.isupper())
myTuple = ("John", "Peter", "Vicky")
print("0".join(myTuple))
print(a.ljust(15),"O")
print(a.lower())
txt = "     banana     "
print("of all fruits", txt.strip(),  "is my favorite")
print("of all fruits", txt.lstrip(),  "is my favorite")
print("of all fruits", txt.rstrip(),  "is my favorite")
print(a.translate(a.maketrans("h" , "j")))
print(a.partition("ll"))
print(a.replace('h', 'l'))
print(a.rfind('l'))
print(a.rindex('o'))
print(a.rjust(20), "O")
print(a.rpartition("l"))
print(a.split("l", 1))
print(a.rsplit("l", 1))
txt = "Thank you for the music\nWelcome to the jungle"
print(txt.splitlines())
print(a.startswith("h"))
print(a.swapcase())
print(a.title())
print(a.upper())
print(a.zfill(20))
